### ISSUE TITLE
Space travelers' hub Kanban

### ISSUE THREAD

**Issue by lisandroseia** [JohnFTitor/space-travelers-hub#30]
Hello, and thanks for taking the time to review this project.
[Kanban for the group capstone](https://github.com/JohnFTitor/space-travelers-hub/projects/1 )
In this project, we are 2 members, @lisandroseia and @JohnFTitor 
Kindly review and let us know if there is something to improve
Thank you so much!
<img src="https://media3.giphy.com/media/I1nwVpCaB4k36/giphy.gif"/>

**Comment by Emmyn5600** [comment]
Hi @lisandroseia and @JohnFTitor

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

- [ ] N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
